// Mekaniker som Scryfall-frågor. Alla körs med prefixet "f:commander ".
module.exports = [
  // ---------- Tokens och spelnivå ----------
  ['T', 'Skapar tokens (alla slag)', '(fo:/\\bcreates?\\b[^.]*\\btokens?\\b/ or fo:/tokens? would be created/ or kw:amass or kw:incubate or kw:investigate or kw:fabricate or kw:afterlife or kw:"living weapon" or kw:populate or kw:embalm or kw:eternalize or kw:myriad or kw:encore or kw:offspring or kw:squad or kw:mobilize or fo:"becomes a token")'],
  ['T', 'Token-dubblare ("tokens would be created")', 'fo:/tokens? would be created/'],
  ['T', 'Fördefinierade tokens (nämner någon av nedan)', '(fo:/\\b(treasures?|foods?|clues?|blood tokens?|maps?|powerstones?|incubators?|gold tokens?|junk tokens?|shard tokens?|landers?|role tokens?)\\b/ or kw:investigate or kw:incubate)'],
  ['T', '  Treasure', 'fo:/\\btreasures?\\b/'],
  ['T', '  Food', 'fo:/\\bfoods?\\b/'],
  ['T', '  Clue / investigate', '(fo:/\\bclues?\\b/ or kw:investigate)'],
  ['T', '  Blood', 'fo:/\\bblood tokens?\\b/'],
  ['T', '  Map', 'fo:/\\bmaps?\\b/'],
  ['T', '  Powerstone', 'fo:/\\bpowerstones?\\b/'],
  ['T', '  Incubator / incubate', '(fo:/\\bincubators?\\b/ or kw:incubate)'],
  ['T', '  Role-tokens', 'fo:/\\brole tokens?\\b/'],
  ['T', 'Token-kopior av kort', '(fo:/tokens? (that\'s|that are) (a )?cop(y|ies)/ or fo:/token cop(y|ies)/ or fo:"becomes a token" or fo:"copies become tokens" or kw:populate or kw:embalm or kw:eternalize or kw:myriad or kw:encore or kw:offspring or kw:squad)'],
  ['T', 'Token ges till annan spelare', '(fo:/(controller|owner|opponent|target player|that player|each player|each other player|chosen player|defending player|they) (may )?creates?\\b[^.]*\\btokens?/ or fo:/tokens?[^.]*under (target|that|an|each) (opponent|player)\'s control/)'],
  ['T', 'Emblem', 'o:emblem'],
  ['T', 'Monarch', 'o:monarch'],
  ['T', 'Initiative', 'o:"the initiative"'],
  ['T', 'Venture into the dungeon', 'o:"venture into the dungeon"'],
  ['T', 'Day/night', '(kw:daybound or kw:nightbound or o:"it becomes day" or o:"it becomes night")'],
  ['T', 'The Ring tempts you', 'o:"the ring tempts you"'],
  ['T', "City's blessing / ascend", '(kw:ascend or o:"city\'s blessing")'],
  ['T', 'Spelnivå-markör (någon av: emblem, monarch, initiative, dungeon, day/night, Ring, blessing, speed)', '(o:emblem or o:monarch or o:"the initiative" or o:"venture into the dungeon" or kw:daybound or o:"it becomes day" or o:"the ring tempts you" or kw:ascend or o:"city\'s blessing" or o:"start your engines")'],

  // ---------- Räknare ----------
  ['C', 'Räknare på permanents (alla slag)', '(fo:/\\bcounters? (on|from)\\b/ or fo:/enters with [^.]*counters?/ or t:planeswalker or t:saga or t:battle or kw:proliferate)'],
  ['C', '  +1/+1-räknare', 'fo:"+1/+1 counter"'],
  ['C', '  -1/-1-räknare', '(fo:"-1/-1 counter" or kw:wither or kw:infect or kw:persist)'],
  ['C', '  Loyalty (planeswalkers)', '(t:planeswalker or o:"loyalty counter")'],
  ['C', '    varav planeswalker-kort', 't:planeswalker'],
  ['C', '  Lore (sagor)', '(t:saga or o:"lore counter")'],
  ['C', '  Charge', 'o:"charge counter"'],
  ['C', '  Time (suspend, vanishing, impending)', '(fo:"time counter" or kw:suspend or kw:vanishing or kw:impending)'],
  ['C', '  Shield', 'o:"shield counter"'],
  ['C', '  Stun', 'o:"stun counter"'],
  ['C', '  Oil', 'o:"oil counter"'],
  ['C', '  Keyword counters (flying, lifelink …)', 'o:/(flying|first strike|double strike|deathtouch|haste|hexproof|indestructible|lifelink|menace|reach|trample|vigilance) counters?/'],
  ['C', '  Proliferate', 'o:proliferate'],
  ['P', 'Räknare på spelare (poison, energy, experience, rad, ticket)', '(o:"poison counter" or kw:infect or kw:toxic or kw:poisonous or o:{E} or o:"energy counter" or o:"experience counter" or o:"rad counter" or o:"ticket counter")'],
  ['P', '  Poison / infect / toxic', '(o:"poison counter" or kw:infect or kw:toxic or kw:poisonous)'],
  ['P', '  Energy', '(o:{E} or o:"energy counter")'],
  ['P', '  Experience', 'o:"experience counter"'],
  ['P', '  Rad', 'o:"rad counter"'],
  ['P', '  Commander damage (nämns i texten)', 'o:/combat damage[^.]*\\bcommander/'],

  // ---------- Fästa och kontroll ----------
  ['A', 'Equipment', 't:equipment'],
  ['A', 'Aura (alla)', 't:aura'],
  ['A', '  Aura på motståndarens creature (Pacifism, Control Magic …)', 't:aura (o:/enchanted (creature|permanent|artifact|land|planeswalker)[^.]*(can\'t attack|can\'t block|doesn\'t untap|activated abilities can\'t|loses all|base power and toughness)/ or o:"you control enchanted" or o:"an opponent controls" or o:/enchanted creature gets -[0-9]+\\/-[1-9]/)'],
  ['A', '  Curse (aura på spelare)', 't:curse'],
  ['A', 'Fäster utan att vara equipment/aura ("attach")', '-t:equipment -t:aura o:/\\battach/'],
  ['A', 'Fortification', 't:fortification'],
  ['A', 'Reconfigure', 'kw:reconfigure'],
  ['A', 'Bestow', 'kw:bestow'],
  ['A', 'Role-tokens (auror som tokens)', 'fo:/\\brole tokens?\\b/'],
  ['K', 'Kontrollbyte (alla slag)', '(o:"gain control of" or o:"gains control of" or o:"exchange control" or o:"you control enchanted" or o:/graveyards?[^.]*onto the battlefield under your control/ or (o:"card in a graveyard" o:"under your control"))'],
  ['K', '  Tillfälligt ("… until end of turn", Threaten)', 'o:/gains? control of[^.]*until end of turn/'],
  ['K', '  Varaktigt (Control Magic, Treachery, "for as long as")', '((o:"gain control of" -o:/gain control of[^.]*until end of turn/) or o:"you control enchanted")'],
  ['K', '  Reanimation ur valfri/motståndares graveyard', '(o:/(from|in) (a|an opponent\'s|any|each opponent\'s|target opponent\'s|all|opponents\') graveyards?[^.]*onto the battlefield under your control/ or o:/onto the battlefield under your control[^.]*from (a|an opponent\'s|any|all) graveyards?/ or (o:"card in a graveyard" o:"under your control"))'],
  ['K', '  Donate / exchange (ger bort)', '(o:"exchange control" or o:/(target|that|an|each) (player|opponent) gains control of/)'],
  ['K', 'Spelar kort som motståndaren äger', '(o:"you don\'t own" or o:"an opponent owns" or o:"your opponents own" or o:/cast[^.]*from (an opponent\'s|opponents\'|their) graveyards?/ or (o:/(target|each|an) opponent\'s library/ o:/you may (cast|play)/) or (o:/exile (another |up to one )?target (artifact|creature|nonland permanent|permanent)/ o:/you may (cast|play) (that|the exiled) card/) or (o:"an opponent" o:"you may play those cards"))'],
  ['K', 'Battle-kort', 't:battle'],
  ['K', 'Goad', 'o:goad'],
  ['K', 'Suspect', 'o:/\\bsuspect/'],

  // ---------- Zoner ----------
  ['Z', 'Exile av permanents (removal)', '((o:/exiles? [a-z, -]*target [a-z, -]*(creature|permanent|artifact|enchantment|planeswalker|battle)s?[.,;]/ or o:/exiles? [a-z, -]*target [a-z, -]*(creature|permanent|artifact|enchantment|planeswalker)s? (you|an|or|and|with|that|until|without|each|of|your|they|it|to|defending)\\b/ or o:/exile (all|each) [a-z, -]*(creatures|permanents|artifacts|enchantments|planeswalkers)/ or o:/exile (that|the) (creature|permanent)\\b/) -o:/return (it|that card|those cards|them|the exiled cards?) to the battlefield/)'],
  ['Z', '  "… until ~ leaves the battlefield" (O-Ring)', '(o:/until [^.]*leaves the battlefield/ or o:/leaves the battlefield, return the exiled/)'],
  ['Z', 'Exile face down (inkl. foretell, hideaway)', '(fo:/exile[^.]*face down/ or fo:"exiled face down" or fo:"face down in exile" or kw:foretell or kw:hideaway)'],
  ['Z', 'Flicker / blink', '(o:/exile[^.]*, then return (it|that card|them|those cards|the exiled cards?)[^.]* to the battlefield/ or o:/exile[^.]*\\. (at the beginning of the next end step, )?return (it|that card|them|those cards|the exiled cards?|that permanent|that creature)[^.]* to the battlefield/)'],
  ['Z', 'Spelar ur graveyard (flashback, escape, "cast from your graveyard" …)', '(kw:flashback or kw:escape or kw:unearth or kw:disturb or kw:embalm or kw:eternalize or kw:jump-start or kw:retrace or kw:aftermath or kw:encore or kw:scavenge or kw:harmonize or kw:mayhem or o:/(cast|play)[^.]*from (your|a|any) graveyards?/ or o:/(has|have|gains?) (flashback|escape|unearth|retrace|jump-start|disturb)/)'],
  ['Z', '  varav nyckelord (flashback, escape, unearth …)', '(kw:flashback or kw:escape or kw:unearth or kw:disturb or kw:embalm or kw:eternalize or kw:jump-start or kw:retrace or kw:aftermath or kw:encore or kw:scavenge or kw:harmonize or kw:mayhem)'],
  ['Z', 'Reanimation (graveyard → battlefield)', '(o:/from (your|a|any|target player\'s|their|an opponent\'s|all|each player\'s) graveyards? (to|onto) the battlefield/ or o:/(return|put)[^.]*(to|onto) the battlefield[^.]*from (your|a|any|their) graveyards?/ or (o:/card in (a|your) graveyard/ o:"to the battlefield"))'],
  ['Z', 'Regrowth (graveyard → hand)', 'o:/from (your|a) graveyard to (your|its owner\'s|their) hand/'],
  ['Z', 'Spelar ur exile (adventure, foretell, impulse draw …)', '(is:adventure or kw:foretell or kw:suspend or kw:plot or kw:warp or kw:rebound or kw:airbend or o:/exile[^.]*\\. (until [^.]*, )?(you may|you can) (play|cast)/ or o:/you may (play|cast)[^.]*(exiled with|from exile|cards exiled)/ or o:/(play|cast)[^.]*from exile/)'],
  ['Z', '  Impulse draw ("exile the top … you may play")', 'o:/exile the top [^.]*cards? of [^.]*librar(y|ies)[^.]*\\. (until [^.]*, )?(you may|you can) (play|cast)/'],
  ['Z', '  Adventure / foretell / suspend / plot / warp', '(is:adventure or kw:foretell or kw:suspend or kw:plot or kw:warp)'],
  ['Z', 'Discard', 'o:/\\bdiscards?\\b/'],
  ['Z', 'Räknar kort i graveyard (delve, threshold, descend …)', '(kw:delve or kw:threshold or kw:delirium or kw:descend or kw:"fathomless descent" or kw:undergrowth or o:/(number of|for each|seven or more|four or more|card types among)[^.]*cards? in [^.]*graveyards?/ or o:/descend [0-9]/)'],
  ['Z', 'Commander-zonen: partner / background / companion', '(o:/\\bpartner\\b/ or kw:"friends forever" or kw:"choose a background" or kw:companion or t:background or kw:"doctor\'s companion")'],
  ['Z', '"commander" i regeltexten', 'o:/\\bcommanders?\\b/'],
  ['Z', 'Sideboard / utanför spelet (learn, lesson, wish)', '(o:/\\blearn\\b/ or o:"outside the game" or t:lesson)'],

  // ---------- Kortformer ----------
  ['F', 'Dubbelsidiga (transform, mdfc, meld, battle)', '(is:transform or is:mdfc or is:meld or t:battle)'],
  ['F', '  layout transform', 'is:transform'],
  ['F', '  layout modal_dfc', 'is:mdfc'],
  ['F', '  layout meld', 'is:meld'],
  ['F', 'Split (inkl. room, fuse, aftermath)', 'is:split'],
  ['F', 'Adventure', 'is:adventure'],
  ['F', 'Flip', 'is:flip'],
  ['F', 'Saga', 't:saga'],
  ['F', 'Class', 't:class'],
  ['F', 'Case', 't:case'],
  ['F', 'Room', 't:room'],
  ['F', 'Prototype', 'kw:prototype'],
  ['F', 'Kopia av annat kort (Clone, "as a copy of")', '(o:/(enter|enters|entering) as a copy of/ or o:"becomes a copy of" or o:"as a copy of")'],
  ['F', 'Nedvänt på bordet: morph/megamorph/disguise/manifest/cloak', '(kw:morph or kw:megamorph or kw:disguise or kw:manifest or kw:"manifest dread" or kw:cloak or o:/\\bmanifests?\\b/ or o:/\\bcloaks?\\b/ or o:/face.down (creature|permanent)/ or o:/turn[^.]*face down/)'],
  ['F', 'Phasing', '(kw:phasing or o:/\\bphases? (out|in)\\b/)'],
  ['F', 'Mutate', 'kw:mutate'],
  ['F', 'Vehicles / crew', '(t:vehicle or kw:crew)'],
  ['F', 'Spacecraft / station', '(t:spacecraft or kw:station)'],
  ['F', '"doesn\'t untap during … untap step"', 'o:/(doesn\'t|don\'t) untap during/'],
];
